#!/bin/bash

heroku pg:backups:capture -a cavaret
heroku pg:backups:download -a cavaret
docker exec -i cavaret_db_1 pg_restore --verbose --clean --no-acl --no-owner -U postgres -d postgres < latest.dump 
./manage migrate