# Generated by Django 3.0.6 on 2020-05-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200514_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joined_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
