# Generated by Django 3.0.6 on 2020-05-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200515_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
