# Generated by Django 3.0.7 on 2020-06-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200609_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tax_id',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
