# Generated by Django 3.1.1 on 2020-09-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200622_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
